### ISSUE TITLE
getZoom, getFocus, getShutter

### ISSUE THREAD

**Issue by f-rank** [schoolpost/BlueMagic32#1]
Hi, was trying the examples and changed one to try and get values for the zoom, focus and shutter, though those don't show up. F-Stop and White Balance do show up.

When I use zoom on the Ursa Broadcast it does refresh the M5stickc screen and doesn't refresh after it hits the start and the end of the zoom, so I guess the change is detected. But for some reason I don't get values.

I tried:
printOnScreen(0, 16, String(BMDControl->getShutter()) + "°");
printOnScreen(0, 32, String(BMDControl->getZoom()));
printOnScreen(0, 48, String(BMDControl->getFocus()));

Probably missing something really basic here, maybe it is the B4 implementation on this particular model, but would appreciate any help on this issue. Thanks.

**Comment by schoolpost** [comment]
hi f-rank,

Good catch, I forgot to document but these are methods that are not completely implemented yet. 

Csaba Nagy

**Comment by f-rank** [comment]
Thank you for taking the time to explain, and for the all around awesomeness.
