### ISSUE TITLE
complete noob

### ISSUE THREAD

**Issue by NYCTY** [schoolpost/BlueMagic32#2]
Hello, I'm using the M5StickC to create a controller for the Blackmagic Pocket 6K, but it's not recognizing the stick via port (I think - attached).  I've installed all the necessary, but maybe there's a step or setup element I'm missing since the video is using a different device.  Any help would be appreciated.

<img width="278" alt="Screen Shot 2020-06-16 at 2 30 35 PM" src="https://user-images.githubusercontent.com/67020907/84813633-3bda8a80-afde-11ea-8314-939642131816.png">

**Comment by schoolpost** [comment]
For some reason your mac is not detecting the serial port. You can maybe try different port on your computer or maybe you are missing the driver for the serial chip. I would consult google to see others remedies to this issue.
